version: "3.8"
services:
  app:
    build: .
    image: sharepoint-salsify-integration:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
